backend:
  name: github
  repo: devanandb/jimnieters-online

media_folder: static/images
public_folder: images
publish_mode: editorial_workflow

collections:
  - name: Article
    label: Article
    folder: content/case-studies
    identifier_field: fields.slug
    create: true
    editor:
      preview: false
    fields:
      - { name: article_id, label: Article ID, widget: number }
      - { name: title, label: Title }
      - { name: tagline, label: Tagline, widget: string }
      - { name: slug, label: Slug }
      - { name: image, label: Image, widget: image}
      - { name: image_caption, label: Image Caption, widget: string}
      - { name: summary, label: Summary, widget: text }
      - name: case_study
        label: Case Study
        widget: object
        fields:
          - label: Problem
            name: problem
            widget: markdown
          - label: Solution
            name: solution
            widget: markdown
          - label: Impact
            name: impact
            widget: markdown
          - label: Points
            name: points
            widget: list
            fields: 
              - { label: Name, name: name, widget: string }
              - { label: Value, name: value, widget: markdown }
          - label: Images
            name: images
            widget: list
            fields:
              - { label: Image, name: src, widget: image }
              - { label: Title, name: title, widget: string }
      - { name: body, label: Body, widget: markdown }
      - { name: order, label: Order, widget: number }
      - label: Category
        name: category
        widget: select
        options:
          - { label: Designer, value: designer }
          - { label: Leader, value: leader }
      - name: tags
        label: Tags, 
        widget: list
        fields:
          - name: tag
            label: Tag
            widget: relation
            collection: tag
            searchFields: ['title']
      - { name: created, label: Created, widget: date }
      - { name: published, label: Published, widget: boolean}
  - name: Tag
    label: Tag
    folder: data/tags
    extension: json
    format: json
    create: true
    editor:
      preview: false
    fields:
      - { name: title, label: Title }
      - { name: slug, label: Slug }

